//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PantoneColorPicker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PantoneColorPicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pantoneColors&quot;: [
        ///    {
        ///    &quot;name&quot;:&quot;black 0961 u&quot;,
        ///    &quot;hex&quot;:&quot;#9D9994&quot;,
        ///    &quot;websafe&quot;:&quot;#999999&quot;,
        ///    &quot;rgb&quot;:{
        ///      &quot;r&quot;: 157,
        ///      &quot;g&quot;: 153,
        ///      &quot;b&quot;: 148
        ///    },
        ///    &quot;hsl&quot;:
        ///    {
        ///      &quot;h&quot;: 33,
        ///      &quot;s&quot;: 4,
        ///      &quot;l&quot;: 60
        ///    },
        ///    &quot;hsb&quot;:
        ///    {
        ///      &quot;h&quot;: 33,
        ///      &quot;s&quot;: 6,
        ///      &quot;b&quot;: 62
        ///    },
        ///    &quot;cmyk&quot;
        ///    :
        ///    {
        ///      &quot;c&quot;: &quot;10&quot;,
        ///      &quot;m&quot;: &quot;10&quot;,
        ///      &quot;y&quot;: &quot;13&quot;,
        ///      &quot;k&quot;: &quot;36&quot;
        ///    }
        ///	  },
        ///{
        ///&quot;name&quot;:&quot;black u&quot;,
        ///		&quot;hex&quot;: &quot;#615D59&quot;,
        ///		&quot;websafe&quot;: &quot;#666666&quot;,
        ///		&quot;rgb&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pantoneUncoatedJson {
            get {
                return ResourceManager.GetString("pantoneUncoatedJson", resourceCulture);
            }
        }
    }
}
